# Generated by Django 5.1.4 on 2025-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0006_alter_studymaterial_file_alter_studymoment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymoment',
            name='image',
            field=models.ImageField(upload_to='ESS/media/study_moments/', verbose_name='Upload image'),
        ),
    ]
