# Generated by Django 5.1.4 on 2025-06-22 02:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0007_alter_studymoment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='study_materials/', verbose_name='Upload File'),
        ),
        migrations.AlterField(
            model_name='studymoment',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='study_moments/', verbose_name='Upload image'),
        ),
    ]
