# Generated by Django 5.1.4 on 2025-06-22 03:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0008_alter_studymaterial_file_alter_studymoment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='study_materials/', verbose_name='Upload File'),
        ),
    ]
