# Generated by Django 5.1.4 on 2025-06-22 03:58

import ESS_app.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0009_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=ESS_app.models.custom_upload_path, verbose_name='Upload File'),
        ),
    ]
