# Generated by Django 5.1.4 on 2025-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100, verbose_name='Branch')),
                ('semester', models.IntegerField(verbose_name='Semester')),
                ('subject_code', models.CharField(max_length=50, verbose_name='Subject Code')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('material_type', models.CharField(max_length=100, verbose_name='Materal Type')),
                ('file', models.FileField(upload_to='study_materials/', verbose_name='Upload File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'unique_together': {('subject_code', 'material_type', 'subject_name')},
            },
        ),
    ]
