# Generated by Django 5.1.4 on 2025-01-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='studymaterials/', verbose_name='Upload File'),
        ),
    ]
