# Generated by Django 5.1.4 on 2025-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0002_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studymaterial',
            unique_together={('material_type', 'subject_code', 'subject_name')},
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='materials/', verbose_name='Upload File'),
        ),
    ]
