# Generated by Django 5.1.4 on 2025-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0004_alter_studymaterial_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='study_moments/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='ESS/ESS/media/studymaterials/', verbose_name='Upload File'),
        ),
    ]
