# Generated by Django 5.1.4 on 2025-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESS_app', '0005_studymoment_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='ESS/media/studymaterials/', verbose_name='Upload File'),
        ),
        migrations.AlterField(
            model_name='studymoment',
            name='image',
            field=models.ImageField(upload_to='ESS/media/study_moments/'),
        ),
    ]
